[package]
name = "polyvis-wasm-wrapper"
version = "0.1.0"
authors = ["zyan0096@student.monash.edu"]
description = "A GeoRust wrapper for my homework"
license = "GPL-3.0-or-later"
repository = "https://github.com/Klaaktu/my-georust-wasm-wrapper"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
geo = { version = "0.31.0", features = ["use-serde"] }
web-sys = { version = "0.3.77", features = [
    "Blob",
    "Document",
    "Element",
    "HtmlAnchorElement",
    "Url",
    'Window',
] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
serde_yaml_ng = "0.10.0"
