name: Nightly release
# Publish to both GitHub releases and the pkg branch (Deno cannot import a zip).

env:
  OUTPUT: polyvis-wasm.7z

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs except the latest.
concurrency:
  group: nightly
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Rust cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            pkg/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install wasm-pack
        run: curl https://drager.github.io/wasm-pack/installer/init.sh -sSf | bash
      - name: Build
        run: wasm-pack build --target web
      # https://github.com/drager/wasm-pack/issues/1502
      - name: Add Deno type declaration
        run: ./add-deno-ts.sh
      - name: Archive
        run: 7z a -mx=9 ${{ env.OUTPUT }} pkg
      # A GitHub release must have a tag
      - name: Move/Create "nightly" tag
        run: |
          git tag --force nightly ${{ github.sha }}
          git push --tags --force
      - name: Refresh release file
        run: gh release upload nightly ${{ env.OUTPUT }} --clobber
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Checkout "pkg" branch
        uses: actions/checkout@v5
        with:
          ref: pkg
          path: pkg-branch
      - name: Update pkg branch
        run: |
          cp -a pkg/. pkg-branch/
          cd pkg-branch/
          rm .gitignore
          git add -A
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "Auto update build artifacts"
          git push
