name: temp script to generate a release attributed to github-action[bot]


env:
  OUTPUT: polyvis-wasm.7z

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: release
        run: gh release create nightly --prerelease -t "Nightly build"
        env:
          GH_TOKEN: ${{ github.token }}
